<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260906072234 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE article (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(180) NOT NULL, excerpt TEXT DEFAULT NULL, content TEXT DEFAULT NULL, category VARCHAR(50) NOT NULL, place VARCHAR(50) NOT NULL, source_url VARCHAR(500) DEFAULT NULL, video_url VARCHAR(500) DEFAULT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_verified BOOLEAN DEFAULT true NOT NULL, verification_label VARCHAR(50) DEFAULT \'Vérifiée\' NOT NULL, is_important BOOLEAN DEFAULT false NOT NULL, view_count INT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, source_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_23A0E66989D9B62 ON article (slug)');
        $this->addSql('CREATE INDEX IDX_23A0E66953C1C61 ON article (source_id)');
        $this->addSql('CREATE INDEX IDX_23A0E6664C19C1 ON article (category)');
        $this->addSql('CREATE INDEX IDX_23A0E66741D53CD ON article (place)');
        $this->addSql('CREATE INDEX IDX_23A0E66E0D4FDE1 ON article (published_at)');
        $this->addSql('CREATE TABLE article_feedback (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, owner_key VARCHAR(64) NOT NULL, interested BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, article_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_87C1B0337294869C ON article_feedback (article_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_feedback_article_owner ON article_feedback (article_id, owner_key)');
        $this->addSql('CREATE TABLE notification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, message TEXT NOT NULL, category VARCHAR(50) DEFAULT NULL, level VARCHAR(20) DEFAULT \'info\' NOT NULL, is_read BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, article_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BF5476CA7294869C ON notification (article_id)');
        $this->addSql('CREATE INDEX IDX_BF5476CADA46F46 ON notification (is_read)');
        $this->addSql('CREATE INDEX IDX_BF5476CA8B8E8428 ON notification (created_at)');
        $this->addSql('CREATE TABLE preference (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, owner_key VARCHAR(64) NOT NULL, topics JSON DEFAULT \'[]\' NOT NULL, zones JSON DEFAULT \'[]\' NOT NULL, frequency VARCHAR(20) DEFAULT \'important\' NOT NULL, notify_email VARCHAR(180) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5D69B053255BB5E3 ON preference (owner_key)');
        $this->addSql('CREATE TABLE source (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(150) NOT NULL, slug VARCHAR(150) NOT NULL, website_url VARCHAR(500) DEFAULT NULL, type VARCHAR(20) DEFAULT \'press\' NOT NULL, reliability_score SMALLINT DEFAULT 80 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5F8A7F73989D9B62 ON source (slug)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE article ADD CONSTRAINT FK_23A0E66953C1C61 FOREIGN KEY (source_id) REFERENCES source (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE article_feedback ADD CONSTRAINT FK_87C1B0337294869C FOREIGN KEY (article_id) REFERENCES article (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CA7294869C FOREIGN KEY (article_id) REFERENCES article (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE article DROP CONSTRAINT FK_23A0E66953C1C61');
        $this->addSql('ALTER TABLE article_feedback DROP CONSTRAINT FK_87C1B0337294869C');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CA7294869C');
        $this->addSql('DROP TABLE article');
        $this->addSql('DROP TABLE article_feedback');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE preference');
        $this->addSql('DROP TABLE source');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
